b8:
    database:
        servers:
            read: DB_HOST
            write: DB_HOST
        name: DB_NAME
        username: DB_USER
        password: 'DB_PASSWORD'
phpci:
    url: 'URL'
    security:
      authentication:
        internal: Internal
    worker:
        host: BEANSTALK_HOST
        queue: BEANSTALK_QUEUE
    email_settings:
        csrf: RANDOM_MD5
        smtp_address: SMTP_HOST
        smtp_port: 'SMTP_PORT'
        smtp_username: SMTP_USER
        smtp_password: SMTP_PASSWORD
        from_address: SMTP_FROM
        default_mailto_address: SMTP_DEFAULTTO
        smtp_encryption: ''
